engines:
  duplication:
    enabled: true
    config:
      languages:
      - ruby
      - javascript
      - python
      - php
  fixme:
    enabled: true
  phpmd:
    enabled: true
    checks:
      CleanCode/StaticAccess:
        enabled: false
      Design/DevelopmentCodeFragment:
        enabled: false
      Controversial/Superglobals:
        enabled: false
      Design/TooManyPublicMethods:
        enabled: false
      CleanCode/StaticAccess:
        enabled: false
      Similar code:
        enabled: false
      Naming/ShortVariable:
        enabled: false
ratings:
  paths:
  - "**.php"
exclude_paths:
- tests/
- .idea/